/** Declaration file generated by dts-gen */

export = nodemailer_express_handlebars;

declare function nodemailer_express_handlebars(options: any): any;

declare namespace nodemailer_express_handlebars {
    const prototype: {
    };

}

